# Generated by Django 4.2.9 on 2024-01-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_student_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.instructor",
            ),
        ),
    ]
