# Generated by Django 4.2.9 on 2024-01-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_instructor_courses_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course',
            new_name='courses',
        ),
    ]
