# Generated by Django 4.2.9 on 2024-01-17 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_coursemanagement_contentupload_contentmanagement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentmanagement",
            old_name="content_upload",
            new_name="content_uploads",
        ),
    ]
