# Generated by Django 4.2.9 on 2024-01-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_rename_content_upload_contentmanagement_content_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmanagement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
