# Generated by Django 4.2.9 on 2024-01-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contentmanagement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmanagement',
            name='user',
        ),
    ]
