# Generated by Django 4.2.9 on 2024-01-19 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_contentupload_content_profile_chatmessage"),
        ("api", "0012_assessment_alter_contentupload_content_submission_and_more"),
    ]

    operations = []
