# Generated by Django 4.2.9 on 2024-01-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_courseevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseevent",
            name="calendar_event_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
