# Generated by Django 4.2.9 on 2024-01-26 01:13

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_courseevent_calendar_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentupload",
            name="content",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="content/",
                validators=[
                    api.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mkv",
                            "webm",
                            "avi",
                            "pdf",
                            "txt",
                            "jpg",
                            "png",
                            "docx",
                            "xlsx",
                            "doc",
                        ]
                    ),
                ],
            ),
        ),
    ]
