# Generated by Django 4.2.9 on 2024-01-26 04:07

import django.core.validators
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_contentupload_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentupload",
            name="content",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="content/",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mkv",
                            "webm",
                            "avi",
                            "pdf",
                            "txt",
                            "jpg",
                            "png",
                            "docx",
                            "xlsx",
                            "doc",
                        ]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coursemanagement",
            name="course_doc",
            field=models.FileField(
                default="course_doc.jpg",
                upload_to="course_doc",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "svg", "webp"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coursemanagement",
            name="course_video",
            field=models.FileField(
                default="course_doc.mp4",
                upload_to="course_doc",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mkv", "webm", "avi"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.FileField(
                default="profile.jpg",
                upload_to="profile",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "svg", "webp"]
                    ),
                ],
            ),
        ),
    ]
