# Generated by Django 4.2.9 on 2024-01-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_courserating"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="completion_status",
            field=models.BooleanField(default=False),
        ),
    ]
