# Generated by Django 4.2.9 on 2024-02-01 15:16

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_contentupload_course_alter_contentupload_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentupload",
            name="content",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="content/course",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "jpeg",
                            "mkv",
                            "webm",
                            "avi",
                            "pdf",
                            "txt",
                            "jpg",
                            "png",
                            "docx",
                            "xlsx",
                            "doc",
                        ]
                    ),
                ],
            ),
        ),
    ]
