# Generated by Django 4.2.9 on 2024-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_contentupload_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="requirements1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="requirements2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="requirements3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="requirements4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="requirements5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
