# Generated by Django 4.2.9 on 2024-02-06 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_courses_difficulty"),
        ("api", "0025_category_category_img_courses_course_img"),
    ]

    operations = []
