# Generated by Django 4.2.9 on 2024-02-07 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="price",
        ),
    ]
