# Generated by Django 4.2.9 on 2024-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_remove_courses_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="price",
            field=models.FloatField(default=100.0),
        ),
    ]
