# Generated by Django 4.2.9 on 2024-02-09 13:43

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_courses_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_img",
            field=models.FileField(
                blank=True,
                default="category.jpg",
                null=True,
                upload_to="category",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "svg", "webp", "jpeg"]
                    ),
                ],
            ),
        ),
    ]
