# Generated by Django 4.2.9 on 2024-02-09 14:03

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_alter_category_category_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="price",
        ),
        migrations.AddField(
            model_name="courses",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courses",
            name="set_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_img",
            field=models.FileField(
                blank=True,
                default="course.jpg",
                null=True,
                upload_to="course",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "svg", "webp", "jpeg"]
                    ),
                ],
            ),
        ),
    ]
