# Generated by Django 4.2.9 on 2024-02-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_remove_courses_price_courses_is_started_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="price",
            field=models.IntegerField(default=100.0),
        ),
    ]
