# Generated by Django 4.2.9 on 2024-02-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_courses_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="duration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
