# Generated by Django 4.2.9 on 2024-02-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_courserequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="interval",
            field=models.CharField(
                choices=[
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Yearly", "Yearly"),
                ],
                default="weekly",
                help_text="weekly, monthly, yearly",
                max_length=20,
            ),
        ),
    ]
