# Generated by Django 4.2.9 on 2024-02-17 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_module_contentupload_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="course",
        ),
        migrations.AddField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="date_updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="module",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="is_ending_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="is_starting_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
