# Generated by Django 4.2.9 on 2024-02-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseevent",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
