# Generated by Django 4.2.9 on 2024-02-24 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_modules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modules",
            name="user",
        ),
    ]
