# Generated by Django 4.2.9 on 2024-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_remove_module_course_module_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="created_at",
            new_name="date_uploaded",
        ),
        migrations.RenameField(
            model_name="module",
            old_name="name",
            new_name="module_name",
        ),
        migrations.RemoveField(
            model_name="contentupload",
            name="module",
        ),
        migrations.RemoveField(
            model_name="module",
            name="description",
        ),
        migrations.AddField(
            model_name="module",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="lessons",
            field=models.ManyToManyField(to="api.contentupload"),
        ),
    ]
