# Generated by Django 4.2.9 on 2024-02-28 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_alter_courseevent_end_date"),
        ("api", "0038_remove_modules_user"),
    ]

    operations = []
