# Generated by Django 4.2.9 on 2024-02-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_rename_created_at_module_date_uploaded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentupload",
            name="course",
        ),
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
    ]
