# Generated by Django 4.2.9 on 2024-03-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0016_remove_question_is_completed_and_more"),
        ("api", "0040_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="quiz",
            field=models.ManyToManyField(to="quiz.question"),
        ),
    ]
