# Generated by Django 4.2.9 on 2024-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0014_alter_assignment_options_and_more"),
        ("api", "0040_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="quiz",
            field=models.ManyToManyField(blank=True, null=True, to="quiz.question"),
        ),
    ]
