# Generated by Django 4.2.9 on 2024-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0014_alter_assignment_options_and_more"),
        ("api", "0041_modules_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modules",
            name="quiz",
            field=models.ManyToManyField(to="quiz.question"),
        ),
    ]
