# Generated by Django 4.2.9 on 2024-03-09 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_contentupload_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modules",
            name="quiz",
        ),
    ]
