# Generated by Django 4.2.9 on 2024-03-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_remove_modules_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
