<<<<<<< HEAD
# Generated by Django 4.2.9 on 2024-01-25 20:06
=======
# Generated by Django 4.2.9 on 2024-01-26 01:13
>>>>>>> e81890cecc3caaf2f52a1f4dfca828d5345f7d5b

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('quiz', '0002_alter_answer_student_alter_quizquestion_category_and_more'),
=======
    dependencies = [
        ("quiz", "0002_alter_answer_student_alter_quizquestion_category_and_more"),
>>>>>>> e81890cecc3caaf2f52a1f4dfca828d5345f7d5b
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='question',
            options={'ordering': ['-id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['-id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ask question'),
=======
            name="question",
            options={
                "ordering": ["-id"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="questioncategory",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="quizquestion",
            options={
                "ordering": ["-id"],
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Ask question"),
>>>>>>> e81890cecc3caaf2f52a1f4dfca828d5345f7d5b
        ),
    ]
