# Generated by Django 4.2.9 on 2024-01-26 04:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0003_alter_question_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_title", models.CharField(max_length=250)),
                ("assignment_description", models.TextField()),
                (
                    "assignment_doc",
                    models.FileField(
                        upload_to="assignment",
                        validators=[
                            utils.validators.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "svg",
                                    "webp",
                                    "pdf",
                                    "docx",
                                    "xlsx",
                                    "doc",
                                    "xls",
                                ]
                            ),
                        ],
                    ),
                ),
                ("date_given", models.DateTimeField()),
                ("date_to_be_submitted", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
