# Generated by Django 4.2.9 on 2024-01-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
