# Generated by Django 4.2.9 on 2024-01-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_question_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
