# Generated by Django 4.2.9 on 2024-01-29 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_assignment_points_question_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="user",
        ),
    ]
