# Generated by Django 4.2.9 on 2024-01-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_courseviewcount"),
        ("quiz", "0007_remove_assignment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.instructor",
            ),
        ),
    ]
