# Generated by Django 4.2.9 on 2024-01-29 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_courseviewcount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0009_remove_assignment_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="points",
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assignment",
                validators=[
                    utils.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "png",
                            "jpg",
                            "svg",
                            "webp",
                            "pdf",
                            "docx",
                            "xlsx",
                            "doc",
                            "xls",
                        ]
                    ),
                ],
            ),
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_submission_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignment",
                        validators=[
                            utils.validators.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "svg",
                                    "webp",
                                    "pdf",
                                    "docx",
                                    "xlsx",
                                    "doc",
                                    "xls",
                                ]
                            ),
                        ],
                    ),
                ),
                ("submission_context", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("points", models.PositiveIntegerField(default=0)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
