# Generated by Django 4.2.9 on 2024-01-30 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0010_remove_assignment_is_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="points",
        ),
        migrations.AddField(
            model_name="answer",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="QuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                ("are_answers", models.ManyToManyField(to="quiz.answer")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
