# Generated by Django 4.2.9 on 2024-02-04 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0013_assignment_is_ended"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ("date_created",)},
        ),
        migrations.AlterModelOptions(
            name="assignmentsubmission",
            options={"ordering": ("date_submitted",)},
        ),
    ]
