# Generated by Django 4.2.9 on 2024-03-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0014_alter_assignment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardForAssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award_name", models.CharField(max_length=255)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.assignmentsubmission",
                    ),
                ),
            ],
        ),
    ]
