# Generated by Django 4.2.9 on 2024-03-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0015_awardforassignmentsubmission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="quizsubmission",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AwardForQuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award_name", models.CharField(max_length=255)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizsubmission",
                    ),
                ),
            ],
        ),
    ]
