# Generated by Django 4.2.9 on 2024-01-20 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumanswer",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="upvotes_answer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UpvoteAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[("Upvote", "Upvote"), ("Downvote", "Downvote")],
                        default="Upvote",
                        max_length=10,
                    ),
                ),
                (
                    "forum_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_answer",
                        to="forum.forumanswer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_upvoted_answer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Upvote Answer",
                "verbose_name_plural": "Upvotes Answer",
            },
        ),
    ]
