# Generated by Django 4.2.9 on 2024-03-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userperformance",
            name="completion_status",
            field=models.CharField(
                choices=[("Completed", "Completed"), ("Uncompleted", "Uncompleted")],
                default="Uncomplete",
                max_length=50,
            ),
        ),
    ]
