# Generated by Django 4.2.9 on 2024-03-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0002_coin_alter_userperformance_completion_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="coin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="performance.coin",
            ),
        ),
    ]
