# Generated by Django 4.2.9 on 2024-03-25 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("performance", "0004_userperformanceformodulecompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userperformance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
