# Generated by Django 4.2.9 on 2024-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0004_alter_coin_gems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gemforeachpoint",
            name="point_for_each_module",
        ),
        migrations.RemoveField(
            model_name="gemforeachpoint",
            name="user",
        ),
        migrations.RemoveField(
            model_name="moduleshighfive",
            name="modules",
        ),
        migrations.RemoveField(
            model_name="moduleshighfive",
            name="user",
        ),
        migrations.RemoveField(
            model_name="pointforeachmodule",
            name="modules_high_five",
        ),
        migrations.RemoveField(
            model_name="pointforeachmodule",
            name="user",
        ),
        migrations.RemoveField(
            model_name="token",
            name="coin",
        ),
        migrations.RemoveField(
            model_name="token",
            name="user",
        ),
        migrations.DeleteModel(
            name="Coin",
        ),
        migrations.DeleteModel(
            name="GemForEachPoint",
        ),
        migrations.DeleteModel(
            name="ModulesHighFive",
        ),
        migrations.DeleteModel(
            name="PointForEachModule",
        ),
        migrations.DeleteModel(
            name="Token",
        ),
    ]
