# Generated by Django 4.2.9 on 2024-03-26 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0005_alter_userperformance_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userperformance",
            name="user",
        ),
    ]
