# Generated by Django 4.2.9 on 2024-02-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartcourses",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
