# Generated by Django 4.2.9 on 2024-02-04 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0008_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordercourse",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="ordercourse",
            name="disenrolled",
        ),
        migrations.RemoveField(
            model_name="ordercourse",
            name="price",
        ),
    ]
