# Generated by Django 4.2.9 on 2024-02-06 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0009_remove_ordercourse_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="orderitem",
        ),
    ]
