# Generated by Django 4.2.9 on 2024-02-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0010_remove_payment_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="ordercourse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="register.ordercourse",
            ),
        ),
    ]
