# Generated by Django 4.2.9 on 2024-02-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0011_payment_ordercourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="ordercourse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="register.ordercourse"
            ),
        ),
    ]
