# Generated by Django 4.2.9 on 2024-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0013_alter_payment_ordercourse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
