# Generated by Django 4.2.9 on 2024-02-16 13:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subscriptions", "0007_subscription_transaction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("coupon_code", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="PlanOnPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("price_override", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("promo_reduction", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                ("is_schedule", models.BooleanField(default=False)),
                ("promo_start", models.DateField()),
                ("promo_end", models.DateField()),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.coupon",
                    ),
                ),
                (
                    "plans_on_promotion",
                    models.ManyToManyField(
                        through="promotion.PlanOnPromotion", to="subscriptions.plan"
                    ),
                ),
                (
                    "promo_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.promotype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planonpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="promotion.promotion"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planonpromotion",
            unique_together={("plan", "promotion")},
        ),
    ]
