# Generated by Django 4.2.9 on 2024-03-04 21:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_modules_quiz"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOnPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("price_override", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.courses"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="plans_on_promotion",
        ),
        migrations.DeleteModel(
            name="PlanOnPromotion",
        ),
        migrations.AddField(
            model_name="courseonpromotion",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="promotion.promotion"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="courses_on_promotion",
            field=models.ManyToManyField(
                through="promotion.CourseOnPromotion", to="api.courses"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseonpromotion",
            unique_together={("course", "promotion")},
        ),
    ]
