# Generated by Django 4.2.9 on 2024-02-08 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_remove_subscription_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
