# Generated by Django 4.2.9 on 2024-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0003_subscription_expiration_date_subscription_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
