# Generated by Django 4.2.9 on 2024-02-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_subscription_pending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
