# Generated by Django 4.2.9 on 2024-02-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0008_remove_subscription_plan_subscription_enrollment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tx_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
