# Generated by Django 4.2.9 on 2024-03-01 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_subscription_price_subscription_tx_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="price",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="tx_ref",
        ),
    ]
